name: 'Add IP to Azure Resources'
description: 'Whitelist IP address in Azure resources (Storage, AKS, KeyVault)'

inputs:
  user_ip:
    description: 'Public IP address to whitelist'
    required: true
  resource_group:
    description: 'Azure Resource Group name'
    required: true
  resource_type:
    description: 'Resource type (storage, aks, keyvault)'
    required: true
  resource_name:
    description: 'Resource name (storage account, AKS cluster, or key vault name)'
    required: false
  azure_credentials:
    description: 'Azure service principal credentials JSON'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}

    - name: Validate IP Address
      shell: bash
      run: |
        USER_IP="${{ inputs.user_ip }}"
        
        # Validate IP format
        if ! echo "$USER_IP" | grep -E '^([0-9]{1,3}\.){3}[0-9]{1,3}$' > /dev/null; then
          echo "Error: Invalid IP address format: $USER_IP"
          exit 1
        fi
        
        # Validate IP octets (0-255)
        IFS='.' read -ra OCTETS <<< "$USER_IP"
        for octet in "${OCTETS[@]}"; do
          if [ "$octet" -gt 255 ] 2>/dev/null || [ "$octet" -lt 0 ] 2>/dev/null; then
            echo "Error: IP address octet out of range (0-255): $USER_IP"
            exit 1
          fi
          if ! [[ "$octet" =~ ^[0-9]+$ ]]; then
            echo "Error: IP address contains non-numeric octet: $USER_IP"
            exit 1
          fi
        done

    - name: Validate Resource Group
      shell: bash
      run: |
        RESOURCE_GROUP="${{ inputs.resource_group }}"
        
        if ! az group show --name "$RESOURCE_GROUP" >/dev/null 2>&1; then
          echo "Resource group $RESOURCE_GROUP not found"
          exit 1
        fi

    - name: Add IP to Storage Account
      if: inputs.resource_type == 'storage'
      shell: bash
      run: |
        RESOURCE_GROUP="${{ inputs.resource_group }}"
        USER_IP="${{ inputs.user_ip }}"
        STORAGE_ACCOUNT="${{ inputs.resource_name }}"
        
        if [ -z "$STORAGE_ACCOUNT" ]; then
          echo "Error: Storage account name is required"
          exit 1
        fi
        
        # Check if storage account exists
        if ! az storage account show --resource-group "$RESOURCE_GROUP" --name "$STORAGE_ACCOUNT" >/dev/null 2>&1; then
          echo "Storage Account $STORAGE_ACCOUNT not found in resource group $RESOURCE_GROUP"
          exit 1
        fi
        
        echo "Processing Storage Account: $STORAGE_ACCOUNT"
        
        # Check if IP already exists
        EXISTING_IPS=$(az storage account show --resource-group "$RESOURCE_GROUP" --name "$STORAGE_ACCOUNT" --query "networkRuleSet.ipRules[].ipAddressOrRange" -o tsv 2>/dev/null || echo "")
        
        if [ -n "$EXISTING_IPS" ] && (echo "$EXISTING_IPS" | grep -q "^$USER_IP$" || echo "$EXISTING_IPS" | grep -q "^$USER_IP/32$"); then
          echo "IP $USER_IP already exists in Storage Account: $STORAGE_ACCOUNT"
          exit 1
        fi

        echo "Adding IP $USER_IP to Storage Account: $STORAGE_ACCOUNT"
        
        if az storage account network-rule add --resource-group "$RESOURCE_GROUP" --account-name "$STORAGE_ACCOUNT" --ip-address "$USER_IP"; then
          echo "Successfully added IP $USER_IP to storage account $STORAGE_ACCOUNT"
        else
          echo "Failed to add IP to storage account $STORAGE_ACCOUNT"
          exit 1
        fi

    - name: Add IP to AKS Cluster
      if: inputs.resource_type == 'aks'
      shell: bash
      run: |
        RESOURCE_GROUP="${{ inputs.resource_group }}"
        USER_IP="${{ inputs.user_ip }}"
        CLUSTER_NAME="${{ inputs.resource_name }}"
        
        if [ -z "$CLUSTER_NAME" ]; then
          echo "Error: AKS cluster name is required"
          exit 1
        fi
        
        # Check if AKS cluster exists
        if ! az aks show --resource-group "$RESOURCE_GROUP" --name "$CLUSTER_NAME" >/dev/null 2>&1; then
          echo "AKS cluster $CLUSTER_NAME not found in resource group $RESOURCE_GROUP"
          exit 1
        fi
        
        # Get current authorized IP ranges
        CURRENT_IPS=$(az aks show --resource-group "$RESOURCE_GROUP" --name "$CLUSTER_NAME" --query "apiServerAccessProfile.authorizedIpRanges" -o tsv 2>/dev/null | tr '\n' ',' | sed 's/,$//' || echo "")
        
        # Check if IP already exists
        if [ -n "$CURRENT_IPS" ] && (echo "$CURRENT_IPS" | grep -q "$USER_IP/32" || echo "$CURRENT_IPS" | grep -q "$USER_IP," || echo "$CURRENT_IPS" | grep -q ",$USER_IP$" || [ "$CURRENT_IPS" = "$USER_IP" ]); then
          echo "IP $USER_IP already exists in AKS $CLUSTER_NAME"
          exit 1
        fi

        echo "Adding IP $USER_IP to AKS Cluster: $CLUSTER_NAME"
        
        # Add the new IP
        if [ -z "$CURRENT_IPS" ]; then
          NEW_IPS="$USER_IP/32"
        else
          NEW_IPS="${CURRENT_IPS},$USER_IP/32"
        fi
        
        if az aks update --resource-group "$RESOURCE_GROUP" --name "$CLUSTER_NAME" --api-server-authorized-ip-ranges "$NEW_IPS"; then
          echo "Successfully added IP $USER_IP to AKS cluster $CLUSTER_NAME"
        else
          echo "Failed to update IP ranges for AKS cluster $CLUSTER_NAME"
          exit 1
        fi

    - name: Add IP to Key Vault
      if: inputs.resource_type == 'keyvault'
      shell: bash
      run: |
        RESOURCE_GROUP="${{ inputs.resource_group }}"
        USER_IP="${{ inputs.user_ip }}"
        KEY_VAULT="${{ inputs.resource_name }}"
        
        if [ -z "$KEY_VAULT" ]; then
          echo "Error: Key vault name is required"
          exit 1
        fi
        
        # Check if key vault exists
        if ! az keyvault show --name "$KEY_VAULT" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
          echo "Key Vault $KEY_VAULT not found in resource group $RESOURCE_GROUP"
          exit 1
        fi
        
        echo "Processing Key Vault: $KEY_VAULT"
        
        # Check if IP already exists
        EXISTING_IPS=$(az keyvault show --name "$KEY_VAULT" --query "properties.networkAcls.ipRules[].value" -o tsv 2>/dev/null || echo "")
        
        if [ -n "$EXISTING_IPS" ] && (echo "$EXISTING_IPS" | grep -q "^$USER_IP$" || echo "$EXISTING_IPS" | grep -q "^$USER_IP/32$"); then
          echo "IP $USER_IP already exists in Key Vault: $KEY_VAULT"
          exit 1
        fi
        
        echo "Adding IP $USER_IP to Key Vault: $KEY_VAULT"
        if az keyvault network-rule add --name "$KEY_VAULT" --ip-address "$USER_IP"; then
          echo "Successfully added IP $USER_IP to key vault $KEY_VAULT"
        else
          echo "Failed to add IP to key vault $KEY_VAULT"
          exit 1
        fi