# Example: How to use modular actions from another repository
name: Whitelist IP in Different Subscription

on:
  workflow_dispatch:
    inputs:
      user_ip:
        description: 'Your public IP address'
        required: true
      resource_group:
        description: 'Azure Resource Group name'
        required: true
      enable_storage:
        description: 'Whitelist in Storage Accounts'
        type: boolean
        default: false
      enable_aks:
        description: 'Whitelist in AKS Clusters'
        type: boolean
        default: false
      enable_keyvault:
        description: 'Whitelist in Key Vaults'
        type: boolean
        default: false

jobs:
  whitelist-resources-external:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Add IP to Storage Accounts (External)
        if: ${{ github.event.inputs.enable_storage == 'true' }}
        uses: your-org/ip-whitelist-repo/.github/actions/add-storage@main
        with:
          user_ip: ${{ github.event.inputs.user_ip }}
          resource_group: ${{ github.event.inputs.resource_group }}
          azure_credentials: ${{ secrets.PROD_AZURE_CREDENTIALS }}
          github_token: ${{ secrets.IP_REPO_TOKEN }}

      - name: Add IP to AKS Clusters (External)
        if: ${{ github.event.inputs.enable_aks == 'true' }}
        uses: your-org/ip-whitelist-repo/.github/actions/add-aks@main
        with:
          user_ip: ${{ github.event.inputs.user_ip }}
          resource_group: ${{ github.event.inputs.resource_group }}
          azure_credentials: ${{ secrets.PROD_AZURE_CREDENTIALS }}
          github_token: ${{ secrets.IP_REPO_TOKEN }}

      - name: Add IP to Key Vaults (External)
        if: ${{ github.event.inputs.enable_keyvault == 'true' }}
        uses: your-org/ip-whitelist-repo/.github/actions/add-keyvault@main
        with:
          user_ip: ${{ github.event.inputs.user_ip }}
          resource_group: ${{ github.event.inputs.resource_group }}
          azure_credentials: ${{ secrets.PROD_AZURE_CREDENTIALS }}
          github_token: ${{ secrets.IP_REPO_TOKEN }}

  cleanup-ips-external:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Remove All IPs (External)
        uses: your-org/ip-whitelist-repo/.github/actions/remove-ip@main
        with:
          azure_credentials: ${{ secrets.PROD_AZURE_CREDENTIALS }}
          github_token: ${{ secrets.IP_REPO_TOKEN }}

# Comments:
# - PROD_AZURE_CREDENTIALS: Different subscription credentials
# - IP_REPO_TOKEN: Token with access to ip-whitelist-repo
# - Each resource type runs independently
# - cleanup-ips-external can be triggered manually to clear all IPs