name: 'Add IP to Storage Accounts'
description: 'Whitelist IP address in Azure Storage Accounts'

inputs:
  user_ip:
    description: 'Public IP address to whitelist'
    required: true
  resource_group:
    description: 'Azure Resource Group name'
    required: true
  azure_credentials:
    description: 'Azure service principal credentials JSON'
    required: true
  github_token:
    description: 'GitHub token for accessing ip-logs branch'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Checkout ip-logs branch
      uses: actions/checkout@v4
      with:
        ref: ip-logs
        token: ${{ inputs.github_token }}

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}

    - name: Pull latest ip-logs updates
      shell: bash
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git pull --rebase origin ip-logs || true

    - name: Add IP to Storage Accounts
      shell: bash
      run: |
        RESOURCE_GROUP="${{ inputs.resource_group }}"
        USER_IP="${{ inputs.user_ip }}"
        
        if ! az group show --name "$RESOURCE_GROUP" >/dev/null 2>&1; then
          echo "Resource group $RESOURCE_GROUP not found"
          exit 1
        fi
        
        touch temp_ips.txt
        
        RESOURCES=$(az storage account list --resource-group "$RESOURCE_GROUP" --query "[].name" -o tsv)
        if [ -z "$RESOURCES" ]; then
          echo "No Storage Accounts found in resource group: $RESOURCE_GROUP"
          exit 0
        fi
        
        for RESOURCE in $RESOURCES; do
          echo "Adding IP to Storage Account: $RESOURCE"
          if ! grep -q "$USER_IP | $RESOURCE | storage" temp_ips.txt 2>/dev/null; then
            az storage account network-rule add --resource-group "$RESOURCE_GROUP" --account-name "$RESOURCE" --ip-address "$USER_IP"
            echo "$USER_IP | $RESOURCE | storage | $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> temp_ips.txt
          else
            echo "IP $USER_IP already logged for $RESOURCE"
          fi
        done

    - name: Commit and push updated IP log
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add temp_ips.txt
        git commit -m "Whitelisted IP ${{ inputs.user_ip }} in Storage Accounts (${{ inputs.resource_group }})" || echo "No changes to commit"
        git push origin ip-logs