name: 'Add IP to Storage Accounts'
description: 'Whitelist IP address in Azure Storage Accounts'

inputs:
  user_ip:
    description: 'Public IP address to whitelist'
    required: true
  resource_group:
    description: 'Azure Resource Group name'
    required: true
  azure_credentials:
    description: 'Azure service principal credentials JSON'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}

    - name: Add IP to Storage Accounts
      shell: bash
      run: |
        RESOURCE_GROUP="${{ inputs.resource_group }}"
        USER_IP="${{ inputs.user_ip }}"
        
        # Validate IP format
        if ! echo "$USER_IP" | grep -E '^([0-9]{1,3}\.){3}[0-9]{1,3}$' > /dev/null; then
          echo "Error: Invalid IP address format: $USER_IP"
          exit 1
        fi
        
        # Check if resource group exists
        if ! az group show --name "$RESOURCE_GROUP" >/dev/null 2>&1; then
          echo "Resource group $RESOURCE_GROUP not found"
          exit 1
        fi
        
        # Get all storage accounts in the resource group
        STORAGE_ACCOUNTS=$(az storage account list --resource-group "$RESOURCE_GROUP" --query "[].name" -o tsv)
        if [ -z "$STORAGE_ACCOUNTS" ]; then
          echo "No Storage Accounts found in resource group: $RESOURCE_GROUP"
          exit 0
        fi
        
        echo "Found storage accounts: $STORAGE_ACCOUNTS"
        
        # Add IP to each storage account
        for ACCOUNT in $STORAGE_ACCOUNTS; do
          echo "Adding IP $USER_IP to Storage Account: $ACCOUNT"
          if az storage account network-rule add --resource-group "$RESOURCE_GROUP" --account-name "$ACCOUNT" --ip-address "$USER_IP"; then
            echo "Successfully added IP $USER_IP to storage account $ACCOUNT"
          else
            echo "Failed to add IP to storage account $ACCOUNT (may already exist)"
          fi
        done