name: Add IP to Azure Resources

on:
  workflow_dispatch:
    inputs:
      user_ip:
        description: 'Your public IP address'
        required: true
      resource_group:
        description: 'Azure Resource Group name'
        required: true
      resource_type:
        description: 'Resource type to whitelist'
        required: true
        type: choice
        options:
          - storage
          - aks
          - keyvault

jobs:
  whitelist-ip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout ip-logs branch
        uses: actions/checkout@v4
        with:
          ref: ip-logs
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Pull latest ip-logs updates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull --rebase origin ip-logs || true

      - name: Whitelist IP in Azure Resources
        run: |
          RESOURCE_TYPE="${{ github.event.inputs.resource_type }}"
          RESOURCE_GROUP="${{ github.event.inputs.resource_group }}"
          USER_IP="${{ github.event.inputs.user_ip }}"
          
          # Validate resource group exists
          if ! az group show --name "$RESOURCE_GROUP" >/dev/null 2>&1; then
            echo "Resource group $RESOURCE_GROUP not found"
            exit 1
          fi
          
          # Ensure temp_ips.txt exists
          touch temp_ips.txt
          
          case $RESOURCE_TYPE in
            "storage")
              RESOURCES=$(az storage account list --resource-group "$RESOURCE_GROUP" --query "[].name" -o tsv)
              if [ -z "$RESOURCES" ]; then
                echo "No Storage Accounts found in resource group: $RESOURCE_GROUP"
                exit 0
              fi
              for RESOURCE in $RESOURCES; do
                echo "Adding IP to Storage Account: $RESOURCE"
                if ! grep -q "$USER_IP | $RESOURCE | storage" temp_ips.txt 2>/dev/null; then
                  az storage account network-rule add --resource-group "$RESOURCE_GROUP" --account-name "$RESOURCE" --ip-address "$USER_IP"
                  echo "$USER_IP | $RESOURCE | storage | $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> temp_ips.txt
                else
                  echo "IP $USER_IP already logged for $RESOURCE"
                fi
              done
              ;;
            "aks")
              RESOURCES=$(az aks list --resource-group "$RESOURCE_GROUP" --query "[].name" -o tsv)
              if [ -z "$RESOURCES" ]; then
                echo "No AKS Clusters found in resource group: $RESOURCE_GROUP"
                exit 0
              fi
              for RESOURCE in $RESOURCES; do
                echo "Adding IP to AKS Cluster: $RESOURCE"
                if ! grep -q "$USER_IP | $RESOURCE | aks" temp_ips.txt 2>/dev/null; then
                  CURRENT_IPS=$(az aks show --resource-group "$RESOURCE_GROUP" --name "$RESOURCE" --query "apiServerAccessProfile.authorizedIpRanges" -o tsv | tr '\n' ',' | sed 's/,$//')
                  if echo "$CURRENT_IPS" | grep -q "$USER_IP/32"; then
                    echo "IP $USER_IP already exists in AKS $RESOURCE, logging only"
                    echo "$USER_IP | $RESOURCE | aks | $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> temp_ips.txt
                  else
                    if [ -z "$CURRENT_IPS" ]; then
                      NEW_IPS="$USER_IP/32"
                    else
                      NEW_IPS="${CURRENT_IPS},$USER_IP/32"
                    fi
                    az aks update --resource-group "$RESOURCE_GROUP" --name "$RESOURCE" --api-server-authorized-ip-ranges "$NEW_IPS"
                    echo "$USER_IP | $RESOURCE | aks | $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> temp_ips.txt
                  fi
                else
                  echo "IP $USER_IP already logged for $RESOURCE"
                fi
              done
              ;;
            "keyvault")
              RESOURCES=$(az keyvault list --resource-group "$RESOURCE_GROUP" --query "[].name" -o tsv)
              if [ -z "$RESOURCES" ]; then
                echo "No Key Vaults found in resource group: $RESOURCE_GROUP"
                exit 0
              fi
              for RESOURCE in $RESOURCES; do
                echo "Adding IP to Key Vault: $RESOURCE"
                if ! grep -q "$USER_IP | $RESOURCE | keyvault" temp_ips.txt 2>/dev/null; then
                  az keyvault network-rule add --name "$RESOURCE" --ip-address "$USER_IP"
                  echo "$USER_IP | $RESOURCE | keyvault | $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> temp_ips.txt
                else
                  echo "IP $USER_IP already logged for $RESOURCE"
                fi
              done
              ;;
          esac



      - name: Commit and push updated IP log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add temp_ips.txt
          git commit -m "Whitelisted IP ${{ github.event.inputs.user_ip }} in ${{ github.event.inputs.resource_group }} (${{ github.event.inputs.resource_type }})" || echo "No changes to commit"
          git push origin ip-logs
