name: Add IP to Selected Azure Resources

on:
  workflow_dispatch:
    inputs:
      user_ip:
        description: 'Your public IP address'
        required: true
      resource_group:
        description: 'Azure Resource Group name'
        required: true
      enable_storage:
        description: 'Whitelist in Storage Accounts'
        type: boolean
        default: false
      enable_aks:
        description: 'Whitelist in AKS Clusters'
        type: boolean
        default: false
      enable_keyvault:
        description: 'Whitelist in Key Vaults'
        type: boolean
        default: false
      aks_cluster_name:
        description: 'AKS Cluster Name (required if AKS enabled)'
        required: false

jobs:
  whitelist-resources:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add IP to Storage Accounts
        if: ${{ github.event.inputs.enable_storage == 'true' }}
        uses: ./.github/actions/add-storage
        with:
          user_ip: ${{ github.event.inputs.user_ip }}
          resource_group: ${{ github.event.inputs.resource_group }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Add IP to AKS Clusters
        if: ${{ github.event.inputs.enable_aks == 'true' }}
        uses: ./.github/actions/add-aks
        with:
          user_ip: ${{ github.event.inputs.user_ip }}
          resource_group: ${{ github.event.inputs.resource_group }}
          cluster_name: ${{ github.event.inputs.aks_cluster_name }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Add IP to Key Vaults
        if: ${{ github.event.inputs.enable_keyvault == 'true' }}
        uses: ./.github/actions/add-keyvault
        with:
          user_ip: ${{ github.event.inputs.user_ip }}
          resource_group: ${{ github.event.inputs.resource_group }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}